AWSTemplateFormatVersion: 2010-09-09
Description: ---
Parameters: 
  KeyName:
    Description: The EC2 Key Pair to allow SSH access to the instances
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
Mappings: 
  RegionMap:
    us-east-1:
      HVM64: ami-09d95fab7fff3776c
      HVMG2: ami-0e9089763828757e1
    us-west-1:
      HVM64: ami-04e59c05167ea7bd5
      HVMG2: ami-0d3caf10672b8e870
Resources: 
  DevelopmentSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Development Security Group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: !Ref SSHLocation
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-SG"
  MyVMInstance:
    Type: AWS::EC2::Instance
    Metadata:
      Comment: Deploy a simple tomcat Application
      AWS::CloudFormation::Init:
        config:
          packages:
            yum:
              httpd: []
              mysql-server: []
          files:
            "/var/www/html/index.html":
              content: |
                <html>
                  <body>
                    <h1>Hi there, this is web server with CloudFormation Helper Scripts </h1>
                  </body>
                </html>   
              mode: "000644"
              owner: "root"
              group: "root" 
            "/etc/cfn/cfn-hup.conf":
              content: !Sub |
                [main]
                stack=${AWS::StackId}
                region=${AWS::Region}
                interval=3
              mode: '000400'
              owner: root
              group: root   
            "/etc/cfn/hooks.d/cfn-auto-reloader.conf":
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.MyVMInstance.Metadata.AWS::CloudFormation::Init
                action=/opt/aws/bin/cfn-init -s ${AWS::StackName} -r MyVMInstance --region ${AWS::Region} 
                runas=root        
              mode: "000400"
              owner: "root"
              group: "root"     
          services:
            sysvinit:
              httpd:
                enabled: "true"
                ensureRunning: "true"
              mysqld:
                enabled: 'true'
                ensureRunning: 'true'
              cfn-hup:
                enabled: 'true'
                ensureRunning: 'true'
                files:
                  - /etc/cfn/cfn-hup.conf
                  - /etc/cfn/hooks.d/cfn-auto-reloader.conf
    Properties:
      KeyName: !Ref KeyName
      ImageId: !FindInMap 
        - RegionMap
        - !Ref 'AWS::Region'
        - HVMG2
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref DevelopmentSecurityGroup
      UserData: 
        "Fn::Base64": 
          !Sub |
           #!/bin/bash -ex
           yum update -y aws-cfn-bootstrap
           # Start cfn-init to Install all Metadata content (pacakges, sources, files, commands and services )
           /opt/aws/bin/cfn-init -s ${AWS::StackName} -r MyVMInstance --region ${AWS::Region}
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}"